# Generated by Django 2.2 on 2021-05-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_book_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
    ]
